### ISSUE TITLE
Seperate sound (output) from voice (input) 

### ISSUE THREAD

**Issue by a-rock-lobster** [mw98/alfred-sound-switcher#2]
Thanks for sharing. Very quick to load in comparison to others.

Is it possible to have seperate keywords for the speaker output and the mic input? I find the list of inputs and outputs is often jumbled together which slows down the workflows use for me. 

Thanks again,

**Comment by LampPrinter** [comment]
> Thanks for sharing. Very quick to load in comparison to others.
> 
> Is it possible to have seperate keywords for the speaker output and the mic input? I find the list of inputs and outputs is often jumbled together which slows down the workflows use for me.
> 
> Thanks again,

Download the 1.0.2 version.
In that the list is not jumbled. First the output options and then the input options are listed.

**Comment by mw98** [comment]
The list shouldn't be jumbled in the latest version either, turned off Alfred's result ordering to keep it fixed
