### ISSUE TITLE
Can't query workflow by keywords

### ISSUE THREAD

**Issue by jacksongoode** [mw98/alfred-sound-switcher#3]
It seems a little weird to me that I'm not able to query the workflow by typing "switch"?

**Comment by mw98** [comment]
You could change the keyword that triggers the script filter to 'switch'
<img width="500" alt="Screenshot 2022-11-14 at 12 28 40 PM" src="https://user-images.githubusercontent.com/5422914/201575591-63830efc-eba4-4d6a-8295-1fd9ee00137d.png">

Alternatively if you'd like multiple keywords to work, you could add a keyword input
<img width="500" alt="Screenshot 2022-11-14 at 12 30 16 PM" src="https://user-images.githubusercontent.com/5422914/201575631-22e06b18-efac-4036-92b9-0a4678410163.png">
