### ISSUE TITLE
Notification alternatives

### ISSUE THREAD

**Issue by vitorgalvao** [mw98/alfred-sound-switcher#4]
I see you’re using a Text Area for users to enter a path for `terminal-notifier`. The proper field would be a File Picker, which allows navigating there with a GUI but also allows entering the path directly.

But even then, there are better choices:

* You could assume that whoever has `terminal-notifier` will want to use it, so look for it int the `PATH` and auto-use if available.
* Use [`notificator`](https://github.com/vitorgalvao/notificator), which I’ve built specifically for Alfred workflows to show the icon in notifications.

**Comment by mw98** [comment]
notifcator looks fantastic - will integrate that in the next version
